[package]
name = "sqlsled"
version = "0.1.0"
authors = ["Hans-Martin Will <hwill@acm.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

