[package]
name = "sqlsled"
version = "0.1.0"
authors = ["Hans-Martin Will <hwill@acm.org>"]
edition = "2018"

[dependencies.sled]
path = "../sled"
version = "0.34.6"

[dependencies.vervolg]
path = "../vervolg"
version = "0.1.0"



